############################################################
#
# 文件微服务
# web访问端口号  约定：8004
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/news-dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: qweqwe
    filters: log4j,wall,mergeStat
  data:
    mongodb:
      uri: mongodb://admin:abc123456@127.0.0.1:27017
      database: xichuan-news
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /


############################################################
#
# fastdfs 的配置信息
#
############################################################
fs:
  files-server:
    type: minio
    minio:
      accessKey: admin
      secretKey: 12345678
      consoleUrl: http://192.168.1.122:9000
      apiPort: 9000
      defaultBucket: huoyan